# Generated by Django 5.0.1 on 2024-01-31 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cname", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Design",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("dname", models.CharField(default="jr-1", max_length=10, unique=True)),
                ("dtime", models.CharField(default="", max_length=6)),
                ("im", models.ImageField(upload_to="photos/designs")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pname", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(max_length=30, unique=True)),
                ("desc", models.CharField(blank=True, max_length=100)),
                ("price", models.IntegerField()),
                ("images", models.ImageField(upload_to="photos/products")),
                ("stock", models.IntegerField()),
                ("avail", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.category"
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.design",
                    ),
                ),
            ],
        ),
    ]
