# Generated by Django 5.0.1 on 2024-03-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
