# Generated by Django 5.0.1 on 2024-02-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cartt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartt",
            name="dadd",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
