# Generated by Django 5.0.1 on 2024-02-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cartt", "0002_alter_cartt_dadd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
